spring.application.name=weather-api

spring.datasource.url=jdbc:postgresql://dpg-d8m309hkh4rs73997mf0-a.oregon-postgres.render.com:5432/weatherdb_nkol?sslmode=require
spring.datasource.username=weatheruser
spring.datasource.password=RUeAPMEmWTuOZ0DNCcTOTQ8eJOM7sQVN

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html