spring.application.name=weather-api

spring.datasource.url=jdbc:postgresql://<neon-host>/<database>?sslmode=require
spring.datasource.username=<neon-username>
spring.datasource.password=<neon-password>

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html
